### PR TITLE
feat(adapter): implement bluetooth adapter, closes #34

### LINKED ISSUE #34: [FEATURE REQUEST] Implement bluetooth-adapter.
Currently, I don't have any Bluetooth printer to test, so I can't implement this adapter. If you have a Bluetooth printer and want to help, welcome PR.

> BTW, maybe [`nouble`](https://github.com/noble/noble) is a good choice for this part.

### PR DESCRIPTION
**Pull request by lucasfernog**

### CODE REVIEW

**Comment by dohooo** [comment]
🥳 Thx! At first, maybe you could add a changeset for your changes, and I'll review it later. 

btw, have you tested it?

**Comment by lucasfernog** [comment]
Yeah I did test it :) it can be improved though, like checking for connected state before writing/reading.

**Comment by lucasfernog** [comment]
Offtopic do you know which encoding I should use for portuguese? Tried a bunch but no luck :(

**Comment by dohooo** [comment]
> Offtopic do you know which encoding I should use for portuguese? Tried a bunch but no luck :(

Maybe you can ask to ChatGPT. Hahh.

image

**Comment by salmanma6** [comment]
Is there any unit test case implementation of this?

**Pull request merged**
